### ISSUE TITLE
在iOS下 显示 NaN天NaN小时..... 安卓测试正常

### ISSUE THREAD

**Issue by wangwill** [aprikyblue/Typecho-Plugin-Uptime#1]
iOS: 
![image](https://cloud.githubusercontent.com/assets/9379983/26538377/89f1746c-4485-11e7-9446-e8c3ba350ce3.png)
Andorid:

![image](https://cloud.githubusercontent.com/assets/9379983/26538404/a3a0769c-4485-11e7-8f68-594a4e4989aa.png)

**Comment by wangwill** [comment]
![image](https://cloud.githubusercontent.com/assets/9379983/26538464/0355baca-4486-11e7-8957-12fd3cffdaac.png)

**Comment by sylviax26** [comment]
ios下chrome?

**Comment by wangwill** [comment]
Safari也是同样问题

**Comment by sylviax26** [comment]
看一下我博客显示正常了吗？可以的话我推送

**Comment by wangwill** [comment]
正常了
